package HibernateEntity;
// Generated Mar 30, 2016 6:51:31 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CartProduct generated by hbm2java
 */
@Entity
@Table(name="cart_product"
    ,catalog="web_project"
)
public class CartProduct  implements java.io.Serializable {


     private int idcartProduct;
     private Payment payment;
     private Product product;
     private Users users;
     private int cartProductMount;
     private Date cartProductDate;
     private String productColor;
     private String productSize;

    public CartProduct() {
    }

	
    public CartProduct(int idcartProduct, Payment payment, Product product, Users users, int cartProductMount, Date cartProductDate) {
        this.idcartProduct = idcartProduct;
        this.payment = payment;
        this.product = product;
        this.users = users;
        this.cartProductMount = cartProductMount;
        this.cartProductDate = cartProductDate;
    }
    public CartProduct(int idcartProduct, Payment payment, Product product, Users users, int cartProductMount, Date cartProductDate, String productColor, String productSize) {
       this.idcartProduct = idcartProduct;
       this.payment = payment;
       this.product = product;
       this.users = users;
       this.cartProductMount = cartProductMount;
       this.cartProductDate = cartProductDate;
       this.productColor = productColor;
       this.productSize = productSize;
    }
   
     @Id 

    
    @Column(name="idcart_product", unique=true, nullable=false)
    public int getIdcartProduct() {
        return this.idcartProduct;
    }
    
    public void setIdcartProduct(int idcartProduct) {
        this.idcartProduct = idcartProduct;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="payment_idpayment", nullable=false)
    public Payment getPayment() {
        return this.payment;
    }
    
    public void setPayment(Payment payment) {
        this.payment = payment;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_idproduct", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="users_idusers", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="cart_product_mount", nullable=false)
    public int getCartProductMount() {
        return this.cartProductMount;
    }
    
    public void setCartProductMount(int cartProductMount) {
        this.cartProductMount = cartProductMount;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="cart_product_date", nullable=false, length=10)
    public Date getCartProductDate() {
        return this.cartProductDate;
    }
    
    public void setCartProductDate(Date cartProductDate) {
        this.cartProductDate = cartProductDate;
    }

    
    @Column(name="product_color", length=45)
    public String getProductColor() {
        return this.productColor;
    }
    
    public void setProductColor(String productColor) {
        this.productColor = productColor;
    }

    
    @Column(name="product_size", length=45)
    public String getProductSize() {
        return this.productSize;
    }
    
    public void setProductSize(String productSize) {
        this.productSize = productSize;
    }




}


