package HibernateEntity;
// Generated Mar 31, 2016 9:53:58 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name="payment"
    ,catalog="web_project"
)
public class Payment  implements java.io.Serializable {


     private Integer idpayment;
     private Users users;
     private float paymentTotal;
     private Float paymentDiscount;
     private Date paymentDate;
     private Set cartProducts = new HashSet(0);

    public Payment() {
    }

	
    public Payment(float paymentTotal, Date paymentDate) {
        this.paymentTotal = paymentTotal;
        this.paymentDate = paymentDate;
    }
    public Payment(Users users, float paymentTotal, Float paymentDiscount, Date paymentDate, Set cartProducts) {
       this.users = users;
       this.paymentTotal = paymentTotal;
       this.paymentDiscount = paymentDiscount;
       this.paymentDate = paymentDate;
       this.cartProducts = cartProducts;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idpayment", unique=true, nullable=false)
    public Integer getIdpayment() {
        return this.idpayment;
    }
    
    public void setIdpayment(Integer idpayment) {
        this.idpayment = idpayment;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="users_idusers")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="payment_total", nullable=false, precision=12, scale=0)
    public float getPaymentTotal() {
        return this.paymentTotal;
    }
    
    public void setPaymentTotal(float paymentTotal) {
        this.paymentTotal = paymentTotal;
    }

    
    @Column(name="payment_discount", precision=12, scale=0)
    public Float getPaymentDiscount() {
        return this.paymentDiscount;
    }
    
    public void setPaymentDiscount(Float paymentDiscount) {
        this.paymentDiscount = paymentDiscount;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="payment_date", nullable=false, length=10)
    public Date getPaymentDate() {
        return this.paymentDate;
    }
    
    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="payment")
    public Set<CartProduct> getCartProducts() {
        return this.cartProducts;
    }
    
    public void setCartProducts(Set cartProducts) {
        this.cartProducts = cartProducts;
    }




}


